# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# the defaults for GitHub Pages (which may override what we provide
# here) are given at https://help.github.com/articles/configuring-jekyll/
#
# Site settings
title: Passau Graduate Student Brown Bag Seminar
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pgbbs.github.io" # the base hostname & protocol for your site
repo: "https://github.com/PGBBS/pgbbs.github.io/tree/master" # base for github-repo
github_username:  pgbbs

# Build settings
markdown: kramdown

# Instead of cluttering the root-directy, we put static pages into `_pages`
include: ['_pages']

# permalink defaults
permalink: /:title/

# plugins
gems:
  - jemoji
